#Global settings
permalink: /:categories/:title/

# Site settings
lang: fr
title: "Chopin IO"
description: "Articles, tutoriels et formations de programmation informatique orientés web."
baseurl: "" # Need to be erase after DNS has been set
url: "alexchopin.github.io" # Replace it by kardigan.no

# Other settings
authors:
  alex:
    pseudo: "Alexandre"
    name: "Alexandre CHOPIN"
    email: "alex@chopin.io"
    avatar: http://www.gravatar.com/avatar/1af749821572815a9a644b2699e3f9df
  seb:
    pseudo: "Atinux"
    name: "Sébastien CHOPIN"
    email: "seb@chopin.io"

# External Services settings
google_analytics:

# Build settings
markdown: kramdown
sass:
    style: compressed
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-gravatar
